Lh ycx patch 1
carter-yagemann/ARCUS pull request #10
Opened 2022-04-14 07:53 UTC by lh-ycx

This patch contains the modification described in #9

2022-04-14 13:39 UTC, carter-yagemann requested changes
Hi @lh-ycx, thanks for your PR. Please see my review comments and retest on your end.

2022-04-14 13:39 UTC, carter-yagemann commented on tools/pt/Makefile
> +	cmake -DPTDUMP=ON -DPTXED=ON -DPTTC=ON -DSIDEBAND=ON -DPEVENT=ON -DFEATURE_ELF=ON -DFEATURE_THREADS=ON -DXED_INCLUDE=./obj/wkit/include/xed -DXED_LIBDIR=./obj/ ../libipt/ && \
Now that you're building inside `pt/build`, the relative paths in the cmake command need to be adjusted:

```suggestion
	cmake -DPTDUMP=ON -DPTXED=ON -DPTTC=ON -DSIDEBAND=ON -DPEVENT=ON -DFEATURE_ELF=ON -DFEATURE_THREADS=ON -DXED_INCLUDE=../obj/wkit/include/xed -DXED_LIBDIR=../obj/ ../libipt/ && \
```

2022-04-14 13:39 UTC, carter-yagemann commented on tools/pt/libipt/ptxed/CMakeLists.txt
> +  ../../obj/wkit/include/xed
This line is no longer needed once you fix the relative paths in `tools/pt/Makefile`

```suggestion
```

2022-04-14 13:39 UTC, carter-yagemann commented on tools/pt/libipt/ptxed/CMakeLists.txt
> +  ../../obj/wkit/lib
This line is no longer needed once you fix the relative paths in `tools/pt/Makefile`

```suggestion
```

2022-04-15 02:01 UTC, lh-ycx commented
Thanks for the suggestions. The revision goes well! I think it is ready to merge.

2022-04-15 13:39 UTC, carter-yagemann approved these changes

2022-04-15 13:40 UTC, merged